version: "3.8"
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
      - ./app/node_modules
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true